//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_Masquerade.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Character
    {
        public Character()
        {
            this.Experience_PointsList = new HashSet<Experience_Points>();
            this.Session_Details = new HashSet<Session_Details>();
            this.Character_Details = new HashSet<Character_Details>();
        }
    
        public int System_id { get; set; }
        public int Parent_id { get; set; }
        public int Story_id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Alive { get; set; }
        [Required]
        public string Clan { get; set; }
        [Display(Name="Personal Story")]
        public string Personal_Story { get; set; }
        [Display(Name="Experience Points")]
        public int Experience_Points { get; set; }
        public int EP_Available { get; set; }
        public string Nature { get; set; }
        public string Demeanon { get; set; }
        public string Concept { get; set; }
        public string Generetion { get; set; }
        public string Sire { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual ICollection<Experience_Points> Experience_PointsList { get; set; }
        public virtual ICollection<Session_Details> Session_Details { get; set; }
        public virtual Story Story { get; set; }
        public virtual ICollection<Character_Details> Character_Details { get; set; }
    }
}
