//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_Masquerade.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Character_Details
    {
        public int System_id { get; set; }
        public int Character_id { get; set; }
        public string Section { get; set; }
        public string Name { get; set; }
        public string Specialization { get; set; }
        public Nullable<int> MaxValue { get; set; }
        public Nullable<int> ActualValue { get; set; }

        public virtual Character Character { get; set; }

        public Character_Details(string section, string name, int maxValue, int actualValue)
        {
            this.Section = section;
            this.Name = name;
            this.MaxValue = maxValue;
            this.ActualValue = actualValue;
        }

        public Character_Details() { }
    }
}
