//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_Masquerade.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Chronicle
    {
        public Chronicle()
        {
            this.Sessions = new HashSet<Session>();
        }
    
        public int System_id { get; set; }
        public int Story_id { get; set; }
        [Required]
        public string Name { get; set; }
        public string Description { get; set; }
        [Required]
        public string Status { get; set; }
    
        public virtual Story Story { get; set; }
        public virtual ICollection<Session> Sessions { get; set; }
    }
}
