//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_Masquerade.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class The_MasqueradeEntities : DbContext
    {
        public The_MasqueradeEntities()
            : base("name=The_MasqueradeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Character> Characters { get; set; }
        public virtual DbSet<Chronicle> Chronicles { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<Session_Details> Session_Details { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<Story> Stories { get; set; }
        public virtual DbSet<Experience_Points> Experience_Points { get; set; }
        public virtual DbSet<Character_Details> Character_Details { get; set; }
    }
}
