//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_Masquerade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Experience_Points
    {
        public int Story_id { get; set; }
        public int Character_id { get; set; }
        public int Experience_Point { get; set; }
    
        public virtual Character Character { get; set; }
        public virtual Story Story { get; set; }
    }
}
