//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_Masquerade.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Player
    {
        public Player()
        {
            this.Characters = new HashSet<Character>();
            this.Stories = new HashSet<Story>();
            this.Sessions = new HashSet<Session>();
        }
    
        public int System_Id { get; set; }
        public string Narrator_id { get; set; }
        [Required]
        [Display(Name="User name")]
        public string UserName { get; set; }
        [Display(Name="Full name")]
        public string Full_Name { get; set; }
        [DataType(DataType.EmailAddress)]
        public string eMail { get; set; }
        [Required]
        public string Status { get; set; }
        [Required]
        public string Type { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<Character> Characters { get; set; }
        public virtual ICollection<Story> Stories { get; set; }
        public virtual ICollection<Session> Sessions { get; set; }
    }
}
