//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;

namespace The_Masquerade.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Session
    {
        private The_MasqueradeEntities db = new The_MasqueradeEntities();
        public Session()
        {
            this.Session_Details = new HashSet<Session_Details>();
        }

        public Session(int Story_id)
        {
            this.Session_Details = new HashSet<Session_Details>();
            var CharactersList = db.Characters.Where(c => c.Story_id == Story_id).Where(c => c.Alive == "Alive").Where(c => c.Player.Type == "Player").ToList();

            foreach (var character in CharactersList)
            {
                var session_Details = new Session_Details();
                session_Details.Character_id = character.System_id;
                session_Details.Character = db.Characters.Find(character.System_id);
                this.Session_Details.Add(session_Details);
            }
        }

        public int System_id { get; set; }
        public int Chronicle_id { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime Date { get; set; }
        [Display(Name="Main Notes")]
        public string Notes { get; set; }
        [Display(Name="Extra Notes")]
        public string Extra_Notes { get; set; }

        [Display(Name = "Session's Player")]
        public int Session_Player { get; set; }

        public virtual Chronicle Chronicle { get; set; }
        public virtual ICollection<Session_Details> Session_Details { get; set; }
        public virtual Player Player { get; set; }
    }
}
