//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_Masquerade.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Session_Details
    {
        public int System_id { get; set; }
        public int Character_id { get; set; }
        public int Session_id { get; set; }
        [Display(Name="Experience Points")]
        public int Experience_Points { get; set; }
        [Display(Name="Closing Situation")]
        public string Closing_Situation { get; set; }
    
        public virtual Character Character { get; set; }
        public virtual Session Session { get; set; }
    }
}
