//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_Masquerade.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Story
    {
        public Story()
        {
            this.Characters = new HashSet<Character>();
            this.Chronicles = new HashSet<Chronicle>();
            this.Experience_Points = new HashSet<Experience_Points>();
            this.Players = new HashSet<Player>();
        }
    
        public int System_id { get; set; }
        public string Narrator_id { get; set; }
        [Required]
        public string Name { get; set; }
        public string Description { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<Character> Characters { get; set; }
        public virtual ICollection<Chronicle> Chronicles { get; set; }
        public virtual ICollection<Experience_Points> Experience_Points { get; set; }
        public virtual ICollection<Player> Players { get; set; }
    }
}
